export const LOGIN_USER="LOGIN_USER";
export const LOGIN_USER_SUCCESS="LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE="LOGIN_USER_FAILURE";

export const FETCH_EMPLOYEES="FETCH_EMPLOYEES";
export const FETCH_EMPLOYEES_SUCCESS="FETCH_EMPLOYEES_SUCCESS";
export const FETCH_EMPLOYEES_FAILURE="FETCH_EMPLOYEES_FAILURE";

export const ADD_EMPLOYEE="ADD_EMPLOYEE";

export const FETCH_LOCKS="FETCH_LOCKS";
export const FETCH_LOCKS_SUCCESS="FETCH_LOCKS_SUCCESS";
export const FETCH_LOCKS_FAILURE="FETCH_LOCKS_FAILURE";
