export const LOGIN_USER="LOGIN_USER";
export const LOGIN_USER_SUCCESS="LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE="LOGIN_USER_FAILURE";

export const FETCH_EMPLOYEES="FETCH_EMPLOYEES";
export const FETCH_EMPLOYEES_SUCCESS="FETCH_EMPLOYEES_SUCCESS";
export const FETCH_EMPLOYEES_FAILURE="FETCH_EMPLOYEES_FAILURE";

export const FETCH_LOCKS="FETCH_LOCKS";
export const FETCH_LOCKS_SUCCESS="FETCH_LOCKS_SUCCESS";
export const FETCH_LOCKS_FAILURE="FETCH_LOCKS_FAILURE";

export const CREATE_EMPLOYEE="CREATE_EMPLOYEE";
export const CREATE_EMPLOYEE_SUCCESS="CREATE_EMPLOYEE_SUCCESS";
export const CREATE_EMPLOYEE_FAILURE="CREATE_EMPLOYEE_FAILURE";

export const DELETE_EMPLOYEE="DELETE_EMPLOYEE";
export const DELETE_EMPLOYEE_SUCCESS="DELETE_EMPLOYEE_SUCCESS";
export const DELETE_EMPLOYEE_FAILURE="DELETE_EMPLOYEE_FAILURE";

export const FETCH_EMPLOYEE_KEYS="FETCH_EMPLOYEE_KEYS";
export const FETCH_EMPLOYEE_KEYS_SUCCESS="FETCH_EMPLOYEE_KEYS_SUCCESS";
export const FETCH_EMPLOYEE_KEYS_FAILURE="FETCH_EMPLOYEE_KEYS_FAILURE";

export const DELETE_LOCK="DELETE_LOCK";
export const DELETE_LOCK_SUCCESS="DELETE_LOCK_SUCCESS";
export const DELETE_LOCK_FAILURE="DELETE_LOCK_FAILURE";

export const CREATE_LOCK="CREATE_LOCK";
export const CREATE_LOCK_SUCCESS="CREATE_LOCK_SUCCESS";
export const CREATE_LOCK_FAILURE="CREATE_LOCK_FAILURE";

export const FETCH_LOCK_KEYS="FETCH_LOCK_KEYS";
export const FETCH_LOCK_KEYS_SUCCESS="FETCH_LOCK_KEYS_SUCCESS";
export const FETCH_LOCK_KEYS_FAILURE="FETCH_LOCK_KEYS_FAILURE";

export const UPDATE_EMPLOYEE="UPDATE_EMPLOYEE";
export const UPDATE_EMPLOYEE_SUCCESS="UPDATE_EMPLOYEE_SUCCESS";
export const UPDATE_EMPLOYEE_FAILURE="UPDATE_EMPLOYEE_FAILURE";

export const FETCH_EMPLOYEE="FETCH_EMPLOYEE";
export const FETCH_EMPLOYEE_SUCCESS="FETCH_EMPLOYEE_SUCCESS";
export const FETCH_EMPLOYEE_FAILURE="FETCH_EMPLOYEE_FAILURE";