export const CREATE_EMPLOYEE="CREATE_EMPLOYEE";
export const CREATE_EMPLOYEE_SUCCESS="CREATE_EMPLOYEE_SUCCESS";
export const CREATE_EMPLOYEE_FAILURE="CREATE_EMPLOYEE_FAILURE";

export const DELETE_EMPLOYEE="DELETE_EMPLOYEE";
export const DELETE_EMPLOYEE_SUCCESS="DELETE_EMPLOYEE_SUCCESS";
export const DELETE_EMPLOYEE_FAILURE="DELETE_EMPLOYEE_FAILURE";

export const FETCH_EMPLOYEE="FETCH_EMPLOYEE";
export const FETCH_EMPLOYEE_SUCCESS="FETCH_EMPLOYEE_SUCCESS";
export const FETCH_EMPLOYEE_FAILURE="FETCH_EMPLOYEE_FAILURE";

export const FETCH_EMPLOYEES="FETCH_EMPLOYEES";
export const FETCH_EMPLOYEES_SUCCESS="FETCH_EMPLOYEES_SUCCESS";
export const FETCH_EMPLOYEES_FAILURE="FETCH_EMPLOYEES_FAILURE";

export const UPDATE_EMPLOYEE="UPDATE_EMPLOYEE";
export const UPDATE_EMPLOYEE_SUCCESS="UPDATE_EMPLOYEE_SUCCESS";
export const UPDATE_EMPLOYEE_FAILURE="UPDATE_EMPLOYEE_FAILURE";