export const FETCH_EMPLOYEE_KEYS="FETCH_EMPLOYEE_KEYS";
export const FETCH_EMPLOYEE_KEYS_SUCCESS="FETCH_EMPLOYEE_KEYS_SUCCESS";
export const FETCH_EMPLOYEE_KEYS_FAILURE="FETCH_EMPLOYEE_KEYS_FAILURE";
