export const DELETE_EMPLOYEE_KEY="DELETE_EMPLOYEE_KEY";
export const DELETE_EMPLOYEE_KEY_SUCCESS="DELETE_EMPLOYEE_KEY_SUCCESS";
export const DELETE_EMPLOYEE_KEY_FAILURE="DELETE_EMPLOYEE_KEY_FAILURE";

export const FETCH_EMPLOYEE_KEYS="FETCH_EMPLOYEE_KEYS";
export const FETCH_EMPLOYEE_KEYS_SUCCESS="FETCH_EMPLOYEE_KEYS_SUCCESS";
export const FETCH_EMPLOYEE_KEYS_FAILURE="FETCH_EMPLOYEE_KEYS_FAILURE";

export const DELETE_LOCK_KEY="DELETE_LOCK_KEY";
export const DELETE_LOCK_KEY_SUCCESS="DELETE_LOCK_KEY_SUCCESS";
export const DELETE_LOCK_KEY_FAILURE="DELETE_LOCK_KEY_FAILURE";

export const FETCH_LOCK_KEYS="FETCH_LOCK_KEYS";
export const FETCH_LOCK_KEYS_SUCCESS="FETCH_LOCK_KEYS_SUCCESS";
export const FETCH_LOCK_KEYS_FAILURE="FETCH_LOCK_KEYS_FAILURE";

export const ATTACH_KEY_TO_EMPLOYEE="ATTACH_KEY_TO_EMPLOYEE";
export const ATTACH_KEY_TO_EMPLOYEE_SUCCESS="ATTACH_KEY_TO_EMPLOYEE_SUCCESS";
export const ATTACH_KEY_TO_EMPLOYEE_FAILURE="ATTACH_KEY_TO_EMPLOYEE_FAILURE";

export const UPDATE_EMPLOYEE_KEY="UPDATE_EMPLOYEE_KEY";
export const UPDATE_EMPLOYEE_KEY_SUCCESS="UPDATE_EMPLOYEE_KEY_SUCCESS";
export const UPDATE_EMPLOYEE_KEY_FAILURE="UPDATE_EMPLOYEE_KEY_FAILURE";

export const FETCH_RESERVED_KEYS_FOR_LOCK="FETCH_RESERVED_KEYS_FOR_LOCK";
export const FETCH_RESERVED_KEYS_FOR_LOCK_SUCCESS="FETCH_RESERVED_KEYS_FOR_LOCK_SUCCESS";
export const FETCH_RESERVED_KEYS_FOR_LOCK_FAILURE="FETCH_RESERVED_KEYS_FOR_LOCK_FAILURE";

export const ATTACH_KEY_TO_LOCK="ATTACH_KEY_TO_LOCK";
export const ATTACH_KEY_TO_LOCK_SUCCESS="ATTACH_KEY_TO_LOCK_SUCCESS";
export const ATTACH_KEY_TO_LOCK_FAILURE="ATTACH_KEY_TO_LOCK_FAILURE";

export const FETCH_UNRESERVED_KEYS="FETCH_UNRESERVED_KEYS";
export const FETCH_UNRESERVED_KEYS_SUCCESS="FETCH_UNRESERVED_KEYS_SUCCESS";
export const FETCH_UNRESERVED_KEYS_FAILURE="FETCH_UNRESERVED_KEYS_FAILURE";