export const CREATE_LOCK="CREATE_LOCK";
export const CREATE_LOCK_SUCCESS="CREATE_LOCK_SUCCESS";
export const CREATE_LOCK_FAILURE="CREATE_LOCK_FAILURE";

export const DELETE_LOCK="DELETE_LOCK";
export const DELETE_LOCK_SUCCESS="DELETE_LOCK_SUCCESS";
export const DELETE_LOCK_FAILURE="DELETE_LOCK_FAILURE";

export const FETCH_LOCKS="FETCH_LOCKS";
export const FETCH_LOCKS_SUCCESS="FETCH_LOCKS_SUCCESS";
export const FETCH_LOCKS_FAILURE="FETCH_LOCKS_FAILURE";

export const GET_LOCK_CONFIG="GET_LOCK_CONFIG";
export const GET_LOCK_CONFIG_SUCCESS="GET_LOCK_CONFIG_SUCCESS";
export const GET_LOCK_CONFIG_FAILURE="GET_LOCK_CONFIG_FAILURE";