export const CREATE_LOCK="CREATE_LOCK";
export const CREATE_LOCK_SUCCESS="CREATE_LOCK_SUCCESS";
export const CREATE_LOCK_FAILURE="CREATE_LOCK_FAILURE";

export const DELETE_LOCK="DELETE_LOCK";
export const DELETE_LOCK_SUCCESS="DELETE_LOCK_SUCCESS";
export const DELETE_LOCK_FAILURE="DELETE_LOCK_FAILURE";

export const FETCH_LOCKS="FETCH_LOCKS";
export const FETCH_LOCKS_SUCCESS="FETCH_LOCKS_SUCCESS";
export const FETCH_LOCKS_FAILURE="FETCH_LOCKS_FAILURE";

export const UPDATE_LOCK="UPDATE_LOCK";
export const UPDATE_LOCK_SUCCESS="UPDATE_LOCK_SUCCESS";
export const UPDATE_LOCK_FAILURE="UPDATE_LOCK_FAILURE";
